# Generated by Django 5.2.7 on 2025-10-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_scraperjob_stop_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='workspace',
            field=models.CharField(db_index=True, default='default', max_length=100),
        ),
        migrations.AddField(
            model_name='scraperjob',
            name='workspace',
            field=models.CharField(db_index=True, default='default', max_length=100),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['workspace', '-created_at'], name='scraper_int_workspa_117cf4_idx'),
        ),
        migrations.AddIndex(
            model_name='scraperjob',
            index=models.Index(fields=['workspace', '-started_at'], name='scraper_scr_workspa_2f9b73_idx'),
        ),
    ]
