# Generated by Django 5.2.7 on 2025-10-22 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_graph_interaction_graph_scraperjob_graph_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('initial_variable', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='graph',
        ),
        migrations.RemoveField(
            model_name='scraperjob',
            name='graph',
        ),
        migrations.AddField(
            model_name='interaction',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='scraper.workspace'),
        ),
        migrations.AddField(
            model_name='scraperjob',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='scraper.workspace'),
        ),
        migrations.DeleteModel(
            name='GraphVariable',
        ),
        migrations.DeleteModel(
            name='Graph',
        ),
    ]
