# Generated by Django 5.2.7 on 2025-10-23 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_interaction_workspace_scraperjob_workspace_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='scraper.scraperjob'),
        ),
    ]
